### ISSUE TITLE
Some problems about torch_sampling when running the reproduction code

### ISSUE THREAD

**Issue by geeknco** [DIMESTeam/DIMES#4]
Dear authors,

Your work is quite impressive and insightful. 

After installing all the dependencies as you noted, I still failed to run your reproduction code. Specifically, I ran the command `./tsp{N}_test_{decoder}.sh tsp{N}`, and it reported:

```
Traceback (most recent call last):
  File "./test_AS_MCTS.py", line 1, in <module>
    from inc.tsp_args import *
  File "/home/Documents/DIMES-main/TSP/TSP-KNN/inc/tsp_args.py", line 3, in <module>
    from inc.utils import *
  File "/home/Documents/DIMES-main/TSP/TSP-KNN/inc/utils.py", line 1, in <module>
    from inc.header import *
  File "/home/Documents/DIMES-main/TSP/TSP-KNN/inc/header.py", line 24, in <module>
    import torch_sampling as pysa
ImportError: /home/.conda/envs/dimes/lib/python3.8/site-packages/torch_sampling.cpython-38-x86_64-linux-gnu.so: undefined symbol: _Z15segment_csr_cpuN2at6TensorES0_N3c108optionalIS0_EESs
```
After many trials and reinstallation, the issue persist. So I wonder how to fix it. 

Thanks a lot.

**Comment by geeknco** [comment]
I updated all the pyg-related dependencies to the latest version, and it works.

**Comment by q-rz** [comment]
Thank you for your interest in our work.

We appreciate your valuable feedback about pyg dependency. We will add a notice into the readme file.

**Comment by L-fu-des22** [comment]
> I updated all the pyg-related dependencies to the latest version, and it works.

Hello, I also have the same issue, and I cannot tackle it for a whole day. Can  you provide the specific versions of  the pyg-related dependencies?  Thank you very much.

**Comment by q-rz** [comment]
@L-fu-des22 Thank you for your interest in our work.

> Hello, I also have the same issue, and I cannot tackle it for a whole day. Can you provide the specific versions of the pyg-related dependencies? Thank you very much.

I have already posted the specific versions of dependencies in `README.md`.

To be more specific, my commands to install the dependencies were:

```bash
pip install --no-index torch-scatter==2.0.7 -f https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html
pip install --no-index torch-sparse==0.6.9 -f https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html
pip install --no-index torch-cluster==1.5.9 -f https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html
pip install torch-geometric==2.0.4
pip install ./torch_sampling
```

Does this work for you? If this still does not work, would you mind providing more information about your issue?

**Comment by L-fu-des22** [comment]
Thanks for your so quick response. I will try it again. By the way, can I ask that what's the version of the python? python3.7 or 3.8? Thanks again.

**Comment by L-fu-des22** [comment]
Finall, eventually, the provided code <sh ./tsp500_test_G.sh tsp500> successfully run! After a whole day strugglling! I will write down how I to do so.

1. Use the code `nvcc --version` to check the cuda version. Ensure that the cuda version is cuda11.0. If it is cuda11.0, you will see `Cuda compilation tools, release 11.0`
2. Create the env using conda. My python's version is 3.8.18. 
3. Activate the env.
4. Install Pytorch==1.7.0+cu110 by `pip install torch==1.7.0+cu110 -f https://download.pytorch.org/whl/torch_stable.html`
5. Install pyg-related dependences, mentioned in the response of [q-rz](https://github.com/DIMESTeam/DIMES/issues/4#issuecomment-1862973874). I copy the corresponding commands here: 
```
pip install --no-index torch-scatter==2.0.7 -f https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html
pip install --no-index torch-sparse==0.6.9 -f https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html
pip install --no-index torch-cluster==1.5.9 -f https://pytorch-geometric.com/whl/torch-1.7.0+cu110.html
pip install torch-geometric==2.0.4
pip install ./torch_sampling
```
6. However, the above commands are not enough. Because I meet the error when executing `pip install ./torch_sampling` :
```
/public/home/lih/Tools/anaconda3/envs/DIMES2/compiler_compat/ld: cannot find -l_segment_csr_cpu: No such file or directory
/public/home/lih/Tools/anaconda3/envs/DIMES2/compiler_compat/ld: cannot find -l_segment_csr_cuda: No such file or directory
```
The reason appearing this error under my situation is that, the gcc cannot find the `_segment_csr_cuda.so` and `_segment_csr_cpu.so` in his library. These two .so files are originally in the torch-scatter package. As shown in the line 17 to 21 in the file `TSP/torch_sampling/setup.py `, these two .so files should be copied to the library of gcc, so gcc can compile them. In my implementation, these two .so files are indeed be copied to the gcc's library, however, the gcc cannot recognize the true path, and raise the errors.

The solution is that, after I ensure these two .so file have been moved to the gcc's library, I manually add the absolute path of gcc to the `setup.py` file. The specific implementation is add one line of code after `shutil.copyfile(fsrc, fdst)` in the `setup.py` file: ` libraries = [f'your_gcc_path/usr/lib/x86_64-linux-gnu/_segment_csr_{dev}' for dev in devices]. ` 

Notice that `your_gcc_path` can be found by adding a line of code ater `LIB_PATH = os.getenv('LD_LIBRARY_PATH').split(':')[-1]` in the `setup.py` file: `print(LIB_PATH)`.

7. Another situation is that, the two .so files cannot be copied to the gcc's library due to the permission, at this time, you should install your own gcc, ensuring that you can copy the .so files to the correspongding folder.

That's all, thanks for your reading.

**Comment by q-rz** [comment]
> Finall, eventually, the provided code <sh ./tsp500_test_G.sh tsp500> successfully run! After a whole day strugglling! I will write down how I to do so.

@L-fu-des22 Thank you so much for sharing your valuable experience! This will considerably help others who run the code in the future. I will add a link to your reply into our README so that others can see it as well.

> By the way, can I ask that what's the version of the python? python3.7 or 3.8? Thanks again.

I was using Python 3.7.10 (packaged by `conda-forge`). Thanks for pointing out that this information is missing in our README. I will add it to README, too.
