### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by xyfffff** [DIMESTeam/DIMES#6]
Hi Ruizhong,

I am encountering persistent installation issues with several packages and am reaching out for assistance. I have attempted various combinations of versions for `pytorch`, `scatter`, `sparse`, `cluster`, and `geometric`, but keep running into errors.

The errors vary: sometimes I encounter an issue with `LIB_PATH = os.getenv('LD_LIBRARY_PATH').split(':')[-1]`, other times I face the error `torch_sparse/_convert_cuda.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr9_M_addrefEv`, and at times I run into a segmentation fault as follows:

> ./tsp500_test_G.sh: line 24: 3291898 Segmentation fault (core dumped) python3 ./test_AS_G.py --seed 123456789 --device cuda:0 --n_nodes 500 --knn_k 50 --outer_opt AdamW --outer_opt_lr 0.001 --outer_opt_wd 1e-5 --inner_opt AdamW --inner_opt_lr 0.01 --inner_opt_wd 0.0001 --net_units 32 --net_act silu --emb_agg mean --emb_depth 12 --par_depth 3 --te_net 120 --te_range_l 0 --te_range_r 128 --te_batch_size 10 --te_tune_steps 0 --te_tune_sample_size 500 --te_sample_size 500 --save_name $1.

I am unclear about the root cause of these issues. It could be due to my NVIDIA CUDA version (12.1), my GCC version (11.4), or my operating system (Ubuntu 22.04.2 LTS).

I am unable to install libraries like `scatter`. I am wondering if these libraries are particularly sensitive to hardware configurations? Do you have any suggestions for resolving these issues or any alternative approaches that I might consider?

Thank you for your time and assistance.

Best regards,
Yifan

**Comment by q-rz** [comment]
The segmentation fault seems due to the failed installation of our TSP sampling library. As far as I am aware of, there are two possible causes of your installation issue:
1. Our TSP sampling library depends on a `.so` file in the `torch_scatter` library. You will have to properly install `torch_scatter` before installing our TSP sampling library.
2. The installer `torch_sampling/setup.py` might fail to find the path of that `.so` file. If so, please search for the file manually and add its path to `torch_sampling/setup.py`. Note that there can be two similar `.so` files, one for CPU and the other for GPU. Please use the GPU version.

If you have any questions, please feel free to let me know.
