### ISSUE TITLE
How to test the DIMES for new instances?

### ISSUE THREAD

**Issue by L-fu-des22** [DIMESTeam/DIMES#7]
Hello, authors, could you describe how to use DIMES to solve new instances, like TSP50000? Thank you very much.

**Comment by q-rz** [comment]
Thank you for your interest in our work!

- To train a new model on TSP50000, you can modify the argument `--n_nodes` for `train.py` in `tsp10000_train.sh`.
- To test the trained model on TSP50000, you can modify the argument `--n_nodes` for `test_{decoder}.py` in `tsp10000_test_{decoder}.sh`.

**Notice:** Since the MCTS program was developed by [Fu et al. \(2021\)](https://github.com/Spider-SCNU/TSP), you might need to contact them if it does not work for TSP50000.

**Comment by L-fu-des22** [comment]
Thank you for your response!
